### ISSUE TITLE
Cleanup "com.apple.metadata.mdworker" / "com.apple.mdworker.bundle" files /  macOS stuck progress bar 

### ISSUE THREAD

**Issue by colorenz** [grahampugh/erase-install#167]
Hey can you maybe add a parameter so that the following situation does not happen? Maybe this will help some users.

https://mrmacintosh.com/macos-upgrade-to-big-sur-failed-stuck-progress-bar-fix-prevention/
https://support.addigy.com/hc/en-us/articles/4409284999571-Monterey-and-Big-Sur-macOS-Upgrades-Can-Stall

sudo find /private/var/folders/*/*/C/com.apple.metadata.mdworker -type d | wc -l 
sudo find /private/var/folders/*/*/C/com.apple.mdworker.bundle -type d | wc -l 

rm -rf /private/var/folders/*/*/C/com.apple.mdworker.bundle
rm -rf /private/var/folders/*/*/C/com.apple.metadata.mdworker

Best Regards

colorenz

**Comment by grahampugh** [comment]
To me this would be better as a standalone script, because it's only relevant for High Sierra and Mojave when upgrading to Big Sur, and might even be fixed in 11.6.2. 

It would be easy to call on those specific systems that had the problem from a pre-install, or even potentially using the existing `--preinstall-command` option.

**Comment by colorenz** [comment]
Yeah good point. I will close this Request.
