### ISSUE TITLE
Which version of Install macOS High Sierra.app to download?

### ISSUE THREAD

**Issue by grahampugh** [grahampugh/erase-install#2]
There are currently three different macOS High Sierra installers available, due to multiple forked builds. This makes life very difficult for this script to determine which one to get. I decided to add some logic to the script to attempt to grab the oldest one, which will cover the most Macs. 

But perhaps I should check for the version currently installed on this computer and download this if available, as you really need to run the `startosinstall` using an installer of the same version as is currently installed.

**Comment by perryk** [comment]
I'm sure you are aware however I thought I'd simply confirm your script currently has trouble with the new T2 equipment MacBookPros due to this. The one I received shipped with the forked build and standard 10.13.6 installer is unable to run startosinstall with the eraseinstall option. It reports this standard installer is older then the version of the OS installed currently and stops. 

I've found your script in a search to find a way to wipe the laptop and it also tried to download the older installer and couldn't build the DMG.  I was able however to successfully build a DMG using installinstallmacos.py after manually choosing the right option and wipe the system ok. 

Otherwise, everything looks pretty good, we may upgrade to this rather than using a separate policy to cache the installer.

Cheers.

**Comment by grahampugh** [comment]
Hi @perryk. Funnily enough I addressed this issue this evening, at least partially, despite not seeing your comment until now. Please check out the new README and re-download the script, as it has different and additional options now, including the ability to download the currently-installed version of macOS, if it is still available.  This should provide an automation workflow for forked builds long as you ensure it is on the latest available version before running this script. 

It should also work for beta versions, as long as the version you have on your device is still available via softwareupdate.

**Comment by perryk** [comment]
Awesome, thanks @grahampugh . I'm yet to test it out however I'll do so in the next few days. 

I've looked over the code though and all the new options look great.

Thanks.
