### ISSUE TITLE
Add 3 login attempts for M1 users

### ISSUE THREAD

**Issue by Benek107** [grahampugh/erase-install#216]
**Is your feature request related to a problem? Please describe.**
When running script on M1 user needs to provide a login to the Volume. If user type in wrong password, the whole script will fail without clear message why.

**Describe the solution you'd like**
Add 3 login attempts for M1 users + change error message to explain what happened. For example "Provided password is incorrect. Please re-run the process/script"

**Describe alternatives you've considered**

**Additional context**

**Comment by grahampugh** [comment]
I'm adding a related issue here, that when running the script in Jamf Pro, when the user enters an incorrect password, the script does `exit 1`, but this is not reported to Jamf Pro so the policy appears to succeed. This _may_ be due to the osascript dialog running in the background, so when the user presses OK, that exits 0 and the final process is ended.

**Comment by grahampugh** [comment]
This functionality will be added in 26.1.

**Comment by grahampugh** [comment]
Please try the latest 26.1 upload.

**Comment by Benek107** [comment]
I have tested infinite login and it works fine. Thank you for the implementation
