### ISSUE TITLE
[BUG] Older Hardware ignore's the targeted version instead downloads high sierra (example)

### ISSUE THREAD

**Issue by jcejka11** [grahampugh/erase-install#411]
**Describe the bug**
Currently using erase-install to target Ventura as the preferred version.  Systems 2016 or older are not compatible.  Instead of failing out the command, erase-install is installing macOS High Sierra, which isnt part of the arguments. (--os 13)

**To Reproduce**
Pick a mac system that is 2016 or older, run erase-install with --os 13 as the targeted os version. 

**Expected behavior**
Should fail out as not compatible.  If a user goes to the app store and downloads ventura, it fails within the first few minutes of the download.

**Comment by grahampugh** [comment]
Please can you provide a complete log from one of those systems, and also send me the complete command you used and the version of erase-install (looks like you deleted those sections from the bug report instead of filling them in). I don't have an old system like that so I need to see what it's doing.

**Comment by grahampugh** [comment]
Closed due to inactivity
