### ISSUE TITLE
[FR] User acknowledgement to proceed with install after download/mount/installer creation

### ISSUE THREAD

**Issue by nramo013** [grahampugh/erase-install#447]
**PLEASE NOTE THAT FEATURE REQUESTS ARE ONLY CONSIDERED AGAINST v.28.0+**

**Is your feature request related to a problem? Please describe.**
Users want the ability to continue working while the download is happening but would like to be warned/acknowledge the install so they can save work before the full screen install and reboot happens

**Describe the solution you'd like**
Allow admins to select the option for the download screen to remain in the background (already exists) but then once the download finishes,  prompt the user to ackowledge the next step is about to happen (save any work before proceeding) then proceed with mounting/installer creation

**Describe alternatives you've considered**
A different in house solution that would run the mist-cli standalone while monitoring the download location, then another process to kickoff the installer application

**Additional context**
None

**Comment by grahampugh** [comment]
This option already exists. The `--confirm` option opens a pop-up after the download has completed and before the full-screen preparation phase window exists.

You can also allow users to continue to work while the installer is preparing, by using the `--rebootdelay XY` option, where XY is the time in seconds (minimum 11, max 300). Using this mode, there is a dialog window instead of the full screen window, and then a countdown window which gives them the number of seconds you specified.
