### ISSUE TITLE
Where the log will stores

### ISSUE THREAD

**Issue by mani2care** [grahampugh/erase-install#51]
Hi Pls have an option to store the activity log in the user machine 

like checking conditions and output or error info

pls make it will be helpful full to.

**Comment by grahampugh** [comment]
I have not included a log output in this script. I will consider whether it's worth it. You could run the script like `sudo ./erase-install.sh [args] > /var/log/erase-install.txt` if you want to save the output.

I have also added two new options that can help you test the script. The `--no-fs` option replaces the full-screen jamfHelper screen with a smaller dialog window so that you can look at the output in Terminal (if you are running the command directly in terminal), and the `--test-run` option prevents `startosinstall` from running at all, so you can test all the preparation stages without wiping/reinstalling the machine (it just opens the full-screen jamfHelper dialog for 2 minutes and then exits).

**Comment by mani2care** [comment]
yep, thanks but then im use this script manually fine but via jamf this will not help to do the saving the output.

looking forwarded instant output like download timing and what percentage, and with continent downloading 

so the end-user/admin will aware of the output stage other than downloading or failing.

**Comment by grahampugh** [comment]
v0.19.0 now outputs everything to `/var/log/erase-install.sh` in addition to the standard output.
